// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApoMYnC59U1GA3NBgYIw1cAsaCm0fByiU',
    appId: '1:143688932069:web:9f9cd6da697a5a6b3a920c',
    messagingSenderId: '143688932069',
    projectId: 'flutter-project-89bd6',
    authDomain: 'flutter-project-89bd6.firebaseapp.com',
    storageBucket: 'flutter-project-89bd6.appspot.com',
    measurementId: 'G-FHHM1WTH2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFc45HBpROc76hX0tMdCWfS9zQa4JnleE',
    appId: '1:143688932069:android:be8adb9cef821dee3a920c',
    messagingSenderId: '143688932069',
    projectId: 'flutter-project-89bd6',
    storageBucket: 'flutter-project-89bd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvpIp-SN3zV_6GfUvvu9QE6nDRKHWvkqM',
    appId: '1:143688932069:ios:4abcb998e469fbea3a920c',
    messagingSenderId: '143688932069',
    projectId: 'flutter-project-89bd6',
    storageBucket: 'flutter-project-89bd6.appspot.com',
    iosClientId: '143688932069-lhg2csr1qi519nnrhjn7jeeft3e3sbjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvpIp-SN3zV_6GfUvvu9QE6nDRKHWvkqM',
    appId: '1:143688932069:ios:4abcb998e469fbea3a920c',
    messagingSenderId: '143688932069',
    projectId: 'flutter-project-89bd6',
    storageBucket: 'flutter-project-89bd6.appspot.com',
    iosClientId: '143688932069-lhg2csr1qi519nnrhjn7jeeft3e3sbjo.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes2',
  );
}
